# Pull the Node image from Docker Hub
FROM node:16.15.1

# Setting Working Directory
WORKDIR /usr/api

# Copying only package.json
COPY package*.json ./

# Install Dependencies
RUN npm install

# Copy rest of the code to container
COPY . .

EXPOSE 8080

# Run the API on Nodemon
CMD ["npm", "run", "dev"]